on:
  workflow_call:
    inputs:
      tuf-version:
        required: true
        type: string
name: Get the latest TUF specification release and open an issue (if needed)
jobs:
  check-spec-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/github-script@9ac08808f993958e9de277fe43a64532a609130e
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: "theupdateframework",
              repo: "specification"
            });
            const spec_version = release.data.tag_name
            const supported_version = "${{ inputs.tuf-version }}"
            const repo = context.repo.owner + "/" + context.repo.repo
            if (spec_version != supported_version) {
              console.log(
                "The latest TUF specification version (" + spec_version + ") does not match with the version that " + repo + " supports (" +
                  supported_version + ")"
              )
              const issues = await github.rest.search.issuesAndPullRequests({
                q: "TUF+specification+has+a+new+version+in:title+state:open+type:issue+repo:" + repo,
              })
              if (issues.data.total_count > 0) {
                console.log("There's already an open issue for that, therefore not creating.")
              } else {
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: "TUF specification has a new version - " + spec_version,
                  body: "Hey, it seems there's a newer version of the TUF specification - [" + spec_version +
                        "](https://github.com/theupdateframework/specification/blob/" + spec_version + "/tuf-spec.md)" +
                        "\n\n" + 
                        "For comparison, the version which [" + repo + "](https://github.com/" + repo + ") state it supports is - [" + supported_version +
                        "](https://github.com/theupdateframework/specification/blob/" + supported_version + "/tuf-spec.md)" + 
                        "\n\n" +
                        "Please review the newer version and address the changes."
                })
                console.log("New issue created.")
              }
            } else {
              console.log(
                "The latest TUF specification version (" + spec_version + ") matches with the version that " + repo + " supports (" +
                  supported_version + ")"
              )
            }
